// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPCWCsipS7x-BYvXbAopIx9-1Ml-YOIcI',
    appId: '1:52583745718:web:7f88a4322b7e99ddd5be17',
    messagingSenderId: '52583745718',
    projectId: 'alive-streaming',
    authDomain: 'alive-streaming.firebaseapp.com',
    storageBucket: 'alive-streaming.firebasestorage.app',
    measurementId: 'G-7XLBB8KT8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxNzlj5zH9rlgsT1TgQtgOM-pik0fefM',
    appId: '1:52583745718:android:02b0c94bd31019c6d5be17',
    messagingSenderId: '52583745718',
    projectId: 'alive-streaming',
    storageBucket: 'alive-streaming.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAut1kGPBZd9xKrAFM2TLd-09x9UzaJYyY',
    appId: '1:52583745718:ios:05b7a5b717955dc3d5be17',
    messagingSenderId: '52583745718',
    projectId: 'alive-streaming',
    storageBucket: 'alive-streaming.firebasestorage.app',
    iosBundleId: 'com.example.aliveStreaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAut1kGPBZd9xKrAFM2TLd-09x9UzaJYyY',
    appId: '1:52583745718:ios:05b7a5b717955dc3d5be17',
    messagingSenderId: '52583745718',
    projectId: 'alive-streaming',
    storageBucket: 'alive-streaming.firebasestorage.app',
    iosBundleId: 'com.example.aliveStreaming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPCWCsipS7x-BYvXbAopIx9-1Ml-YOIcI',
    appId: '1:52583745718:web:ec093a76e9a3b380d5be17',
    messagingSenderId: '52583745718',
    projectId: 'alive-streaming',
    authDomain: 'alive-streaming.firebaseapp.com',
    storageBucket: 'alive-streaming.firebasestorage.app',
    measurementId: 'G-0FS2Q4EB9K',
  );
}
