/// Firebase-specific runtime constants.
///
/// [googleWebClientId] is the **Web** OAuth 2.0 client ID auto-generated by
/// Firebase when you enable Google sign-in. google_sign_in 7.x requires this
/// on Android in order to return an `idToken` Firebase can exchange.
///
/// How to find it:
///   1. Firebase Console → Authentication → Sign-in method → Google → Enable.
///   2. Expand "Web SDK configuration" — copy the "Web client ID".
///   3. Paste it below, replacing the placeholder.
///
/// (You can also find it in a freshly downloaded `google-services.json` under
///  `client[0].oauth_client[]` where `client_type == 3`.)
class FirebaseConstants {
  FirebaseConstants._();

  static const String googleWebClientId =
      '52583745718-ha38apltr4v0cv3kauncehp2b7arnc8v.apps.googleusercontent.com';
}
